# Generated by Django 3.2.5 on 2022-06-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
        ('mainapp', '0003_product'),
    ]

    operations = [
    ]
